### ISSUE TITLE
browserHTTPRequest is not supported outside the web browser without a fetch polyfill

### ISSUE THREAD

**Issue by j2l** [DavidCai1993/style-transfer.js#3]
After managing to fix the node-gyp error at install (Win10, node 10.13) I stumble on:
```
node ./transfer.js transfer -c ./images/louvre.jpg -s ./images/Francis_Picabia.jpg -o output.jpg --gpu
```
```
2018-12-17 13:23:30.806122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.253
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.31GiB
2018-12-17 13:23:30.813714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-12-17 13:23:31.861445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-17 13:23:31.865286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-12-17 13:23:31.868462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-12-17 13:23:31.871403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3024 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2)
cpu backend was already registered. Reusing existing backend
Error: browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
    at new BrowserHTTPRequest (E:\style-transfer.js\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:48:23)
    at Object.browserHTTPRequest (E:\style-transfer.js\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:278:12)
    at Object.<anonymous> (E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\models.js:102:50)
    at step (E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\models.js:42:23)
    at Object.next (E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\models.js:23:53)
    at E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\models.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\models.js:13:12)
    at Object.loadModelInternal (E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\models.js:96:12)
    at Object.loadModel (E:\style-transfer.js\node_modules\@tensorflow\tfjs-layers\dist\exports.js:17:21)
```
Any idea?

**Comment by eat-full** [comment]
I have the same problem, did you solve it?

**Comment by j2l** [comment]
Nope, I installed another style-transfer for now.
